### ISSUE TITLE
sass going unprocessed?

### ISSUE THREAD

**Issue by edward** [resistorsoftware/Shopify-Developer-Book#1]
@resistorsoftware 

While building the book normally using `kitabu export` I noticed that changing the sass files per the README doesn’t change anything.

Are the sass files being used? I looked through the latest official kitabu repo as well as @jstorimer’s (who’s now a contributor to the @fnando repo and has his changes merged in), but didn’t find any mention of sass.

Is the sass being manually generated into css or am I missing something?

**Comment by edward** [comment]
There’s a missing `compass compile` step, isn’t there?

**Comment by edward** [comment]
All good. Fixed in https://github.com/edward/Shopify-Developer-Book/commit/23eb9abf61fb9bd48aa8e6ab8ce9fff7602faae1

**Comment by resistorsoftware** [comment]
Cool. There are a few ways to skin that cat. I just run compass watch in
terminal when working but your approach is fine too. Thanks!

On Thu, Jun 14, 2012 at 7:42 PM, Edward Ocampo-Gooding <
reply@reply.github.com
